#!/usr/bin/env python3
"""Configure remote access and headless boot; swap changes take effect at reboot."""
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile


def disable_fstab_swap(text):
    lines = []
    for line in text.splitlines(keepends=True):
        fields = line.split()
        if fields and not line.lstrip().startswith('#') and len(fields) >= 3 and fields[2] == 'swap':
            line = '# pi-set-go disabled swap: ' + line
        lines.append(line)
    return ''.join(lines)


def main():
    if os.geteuid() != 0:
        raise SystemExit('Run with sudo.')
    backup = Path(tempfile.mkdtemp(prefix='pi-set-go-remote-', dir='/var/backups'))
    print(f'Configuration backup: {backup}', flush=True)

    def run(*args):
        print('+ ' + ' '.join(args), flush=True)
        return subprocess.run(args, check=True)

    def write(path, text, mode=0o644):
        path = Path(path)
        saved = backup / str(path).lstrip('/')
        saved.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() or path.is_symlink():
            shutil.copy2(path, saved, follow_symlinks=False)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Replace our destination instead of following a preexisting symlink.
        fd, staged = tempfile.mkstemp(prefix='.pi-set-go-', dir=path.parent)
        try:
            with os.fdopen(fd, 'w') as output:
                output.write(text)
            os.chmod(staged, mode)
            os.replace(staged, path)
        finally:
            if os.path.exists(staged):
                os.unlink(staged)

    # Verify SSH before stopping the local display manager. Keep auth policy intact.
    run('/usr/sbin/sshd', '-t')
    run('systemctl', 'enable', '--now', 'ssh')
    run('systemctl', 'is-active', '--quiet', 'ssh')
    run('usermod', '-a', '-G', 'ssl-cert', 'xrdp')
    write('/etc/xrdp/startwm.sh', '''#!/bin/sh
# Generated by pi-set-go: an on-demand, minimal X11 desktop for RDP.
unset DBUS_SESSION_BUS_ADDRESS
unset SESSION_MANAGER
exec dbus-run-session -- openbox-session
''', 0o755)
    run('systemctl', 'enable', '--now', 'xrdp')
    run('systemctl', 'restart', 'xrdp')
    run('systemctl', 'is-active', '--quiet', 'xrdp')
    run('systemctl', 'is-active', '--quiet', 'xrdp-sesman')

    # Record prior service state for manual recovery without stopping SSH.
    (backup / 'default-target').write_text(subprocess.check_output(['systemctl', 'get-default'], text=True))
    run('systemctl', 'set-default', 'multi-user.target')
    display = subprocess.run(['systemctl', 'show', '-p', 'LoadState', '--value', 'display-manager.service'],
                             capture_output=True, text=True, check=True).stdout.strip()
    if display not in ('not-found', ''):
        run('systemctl', 'stop', 'display-manager.service')

    # Keep swap active until reboot, following rpi-swap's documented lifecycle.
    fstab = Path('/etc/fstab')
    write(fstab, disable_fstab_swap(fstab.read_text()))
    write('/etc/rpi/swap.conf.d/99-pi-set-go.conf', '[Main]\nMechanism=none\n')
    # Also cover generic Debian's zram-generator configurations.
    write('/etc/systemd/zram-generator.conf', '# pi-set-go: no zram swap\n')
    sections = {'zram0'}
    for folder in ('/usr/lib/systemd', '/usr/local/lib/systemd', '/run/systemd', '/etc/systemd'):
        candidates = [Path(folder) / 'zram-generator.conf']
        candidates += list((Path(folder) / 'zram-generator.conf.d').glob('*.conf'))
        for path in candidates:
            if path.is_file():
                sections.update(re.findall(r'(?m)^\s*\[(zram[0-9]+)\]', path.read_text()))
    write('/etc/systemd/zram-generator.conf.d/99-pi-set-go.conf',
          ''.join(f'[{name}]\nzram-size = 0\n\n' for name in sorted(sections)))
    units = subprocess.check_output(['systemctl', 'list-unit-files', '--no-legend', '--no-pager'], text=True)
    present = {line.split()[0] for line in units.splitlines() if line.split()}
    for name in ('dphys-swapfile.service', 'zramswap.service', 'systemd-swap.service'):
        if name in present:
            run('systemctl', 'disable', name)
    # Mask specific known swap devices, covering custom .swap units and GPT auto-discovery.
    swap_units = {name for name in present if name.endswith('.swap')}
    for line in Path('/proc/swaps').read_text().splitlines()[1:]:
        device = line.split()[0]
        unit = subprocess.check_output(['systemd-escape', '--path', '--suffix=swap', device], text=True).strip()
        swap_units.add(unit)
    for name in sorted(swap_units):
        # Existing native unit files may prevent masking; retain them in the backup.
        native = Path('/etc/systemd/system') / name
        if native.exists() and not native.is_symlink():
            saved = backup / 'etc/systemd/system' / name
            saved.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(native, saved)
            native.unlink()
        run('systemctl', 'mask', name)

    run('systemctl', 'is-enabled', 'ssh', 'xrdp')
    run('systemctl', 'is-active', 'ssh', 'xrdp', 'xrdp-sesman')
    run('systemctl', 'get-default')
    run('ss', '-lntp')
    print('SSH and xrdp enabled. RDP uses TCP 3389; log in with an existing local user password.')
    print('Openbox: right-click the desktop for the applications menu and terminal.')
    print('Local desktop stopped. Swap disabling is pending reboot; current swap:')
    print(Path('/proc/swaps').read_text())
    print('Reboot when ready, then verify /proc/swaps has only its header.')
    print('Firewall reachability and an authenticated RDP desktop login must be tested from your client.')


if __name__ == '__main__':
    main()
