#!/usr/bin/env python3
"""Generate BIND zones from the active Ethernet address and a local zone list."""
import argparse
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import time


def select_address(addresses, routes, ethernet, interface=None):
    candidates = []
    for item in addresses:
        name = item['ifname']
        if name not in ethernet or 'UP' not in item.get('flags', []):
            continue
        for addr in item.get('addr_info', []):
            if addr.get('family') == 'inet' and addr.get('scope') == 'global':
                if addr.get('preferred_life_time') == 0:
                    continue
                ip = ipaddress.IPv4Interface(f"{addr['local']}/{addr['prefixlen']}")
                if not ip.ip.is_link_local and not ip.ip.is_loopback:
                    candidates.append((name, ip))
    if interface:
        candidates = [c for c in candidates if c[0] == interface]
    else:
        defaults = sorted((r for r in routes if r.get('dst') == 'default'
                           and r.get('dev') in {c[0] for c in candidates}),
                          key=lambda r: r.get('metric', 0))
        if defaults:
            route = defaults[0]
            candidates = [c for c in candidates if c[0] == route['dev']]
            if route.get('prefsrc'):
                candidates = [c for c in candidates if str(c[1].ip) == route['prefsrc']]
    if len(candidates) != 1:
        raise ValueError('Need one Ethernet IPv4 address; use --dns-interface=NAME for multiple interfaces, or remove ambiguous secondary addresses.')
    return candidates[0]


def domains_from(path):
    values = path.read_text().splitlines() if path.exists() else ['super.local']
    domains = []
    for value in values:
        value = value.split('#', 1)[0].strip().lower().rstrip('.')
        if not value:
            continue
        if len(value) > 253 or '.' not in value or any(
            not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label)
            for label in value.split('.')
        ):
            raise ValueError('Invalid domain in local zones.list')
        if value not in domains:
            domains.append(value)
    if not domains:
        raise ValueError('zones.list must contain at least one domain')
    return domains


def zone_text(domain, address, serial):
    return f'''$TTL 300
@ IN SOA ns1.{domain}. hostmaster.{domain}. (
    {serial} ; serial
    3600 900 604800 300 )
@   IN NS ns1.{domain}.
@   IN A {address}
ns1 IN A {address}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('output', type=Path)
    parser.add_argument('--interface')
    parser.add_argument('--dry-run', action='store_true', help='Detect the Ethernet IP and preview files without writing')
    args = parser.parse_args()
    if not args.dry_run:
        if os.geteuid() != 0:
            parser.error('Run with sudo, or use --dry-run to preview on the Pi')
        for command in ('ip', 'named-checkzone', 'named-checkconf', 'systemctl'):
            if not shutil.which(command):
                parser.error(f'Missing {command}; install the required packages on the Pi first')
    domains = domains_from(args.output / 'zones.list')
    addresses = json.loads(subprocess.check_output(['ip', '-j', '-4', 'address', 'show']))
    routes = json.loads(subprocess.check_output(['ip', '-j', '-4', 'route', 'show', 'default']))
    # Physical Ethernet includes USB adapters; exclude Wi-Fi and virtual bridges/veth.
    ethernet = {p.name for p in Path('/sys/class/net').iterdir()
                if (p / 'device').exists() and not (p / 'wireless').exists()
                and (p / 'type').read_text().strip() == '1'}
    interface, address = select_address(addresses, routes, ethernet, args.interface)
    root = Path('/etc/bind')
    local = root / 'named.conf.local'
    options = root / 'named.conf.options'
    managed = root / 'pi-set-go'
    if local.is_symlink() or options.is_symlink() or managed.is_symlink():
        raise ValueError('Custom BIND symlinks require manual review')
    include = 'include "/etc/bind/pi-set-go/zones.conf";'
    current_local = local.read_text() if local.exists() else ''
    active_include = re.search(r'(?m)^\s*' + re.escape(include) + r'\s*$', current_local)
    new_local = current_local if active_include else current_local.rstrip() + '\n\n' + include + '\n'
    new_options = f'''// Generated by pi-set-go from {interface}; regenerated on each run.
options {{
    directory "/var/cache/bind";
    listen-on {{ 127.0.0.1; {address.ip}; }};
    listen-on-v6 {{ none; }};
    allow-query {{ any; }};
    recursion yes;
    allow-recursion {{ localhost; {address.network}; }};
    allow-query-cache {{ localhost; {address.network}; }};
    allow-transfer {{ none; }};
    dnssec-validation auto;
}};
'''
    if args.dry_run:
        print(f'Detected {interface}: {address}')
        print(f'\n{options}:\n{new_options}')
        print(f'{local}:\n{new_local}')
        declarations = []
        for domain in domains:
            target = managed / f'db.{domain}'
            # Actual deployment advances the installed serial when necessary.
            print(f'{target}:\n{zone_text(domain, address.ip, int(time.time()))}')
            declarations.append(f'zone "{domain}" {{ type master; file "{target}"; allow-update {{ none; }}; }};')
        print(f'{managed / "zones.conf"}:\n' + '\n'.join(declarations))
        print('\nPreview only; no files written or services changed. Apply advances existing serials.')
        return
    backup = Path(tempfile.mkdtemp(prefix='pi-set-go-dns-', dir='/var/backups'))
    files = [local, options]
    owners = {p: (p.stat().st_uid, p.stat().st_gid) for p in files}
    for p in files:
        shutil.copy2(p, backup / p.name)
    had_managed = managed.exists()
    if had_managed:
        shutil.copytree(managed, backup / 'zones')
    print(f'DNS: {interface} = {address}; backup: {backup}', flush=True)
    try:
        managed.mkdir(mode=0o755, exist_ok=True)
        declarations = []
        for domain in domains:
            target = managed / f'db.{domain}'
            if target.is_symlink():
                raise ValueError('Managed zone symlink requires manual review')
            old = target.read_text() if target.exists() else ''
            match = re.search(r'(?m)^\s*(\d+)\s*; serial', old)
            serial = max(int(time.time()), int(match[1]) + 1 if match else 1)
            if serial >= 2**32:
                raise ValueError('Zone serial exhausted; manual rollover required')
            target.write_text(zone_text(domain, address.ip, serial))
            target.chmod(0o644)
            subprocess.run(['named-checkzone', domain, str(target)], check=True)
            declarations.append(f'zone "{domain}" {{ type master; file "{target}"; allow-update {{ none; }}; }};')
        zone_config = managed / 'zones.conf'
        if zone_config.is_symlink():
            raise ValueError('Managed include symlink requires manual review')
        zone_config.write_text('\n'.join(declarations) + '\n')
        zone_config.chmod(0o644)
        local.write_text(new_local)
        options.write_text(new_options)
        subprocess.run(['named-checkconf', '-z'], check=True)
        subprocess.run(['systemctl', 'restart', 'named'], check=True)
        subprocess.run(['systemctl', 'is-active', '--quiet', 'named'], check=True)
    except Exception:
        for p in files:
            shutil.copy2(backup / p.name, p)
            os.chown(p, *owners[p])
        shutil.rmtree(managed, ignore_errors=True)
        if had_managed:
            shutil.copytree(backup / 'zones', managed)
        print('Restored DNS configuration; inspect named service status before restarting manually.')
        raise
    # Keep generated copies in the ignored local config directory for review.
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / 'zones').mkdir(exist_ok=True)
    (args.output / 'named.conf.local').write_text(new_local)
    (args.output / 'named.conf.options').write_text(new_options)
    (args.output / 'zones.conf').write_text(zone_config.read_text())
    for domain in domains:
        shutil.copy2(managed / f'db.{domain}', args.output / 'zones' / f'db.{domain}')
    print('DNS configured. Point clients at the Ethernet IP; rerun after its address changes.')


if __name__ == '__main__':
    main()
