#!/usr/bin/env python3
"""Generate BIND zones from the active Ethernet address and a local zone list."""
import argparse
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import time


def select_address(addresses, routes, ethernet, interface=None):
    candidates = []
    for item in addresses:
        name = item['ifname']
        if name not in ethernet or 'UP' not in item.get('flags', []):
            continue
        for addr in item.get('addr_info', []):
            if addr.get('family') == 'inet' and addr.get('scope') == 'global':
                if addr.get('preferred_life_time') == 0:
                    continue
                ip = ipaddress.IPv4Interface(f"{addr['local']}/{addr['prefixlen']}")
                if not ip.ip.is_link_local and not ip.ip.is_loopback:
                    candidates.append((name, ip))
    if interface:
        candidates = [c for c in candidates if c[0] == interface]
    else:
        defaults = sorted((r for r in routes if r.get('dst') == 'default'
                           and r.get('dev') in {c[0] for c in candidates}),
                          key=lambda r: r.get('metric', 0))
        if defaults:
            route = defaults[0]
            candidates = [c for c in candidates if c[0] == route['dev']]
            if route.get('prefsrc'):
                candidates = [c for c in candidates if str(c[1].ip) == route['prefsrc']]
    if len(candidates) != 1:
        raise ValueError('Need one Ethernet IPv4 address; use --dns-interface=NAME for multiple interfaces, or remove ambiguous secondary addresses.')
    return candidates[0]


def domains_from(path):
    if not path.is_file():
        raise ValueError(f'Missing local zone list: {path}. Copy examples/config/dns/zones.list into config/dns/zones.list and edit it first.')
    values = path.read_text().splitlines()
    domains = []
    for value in values:
        value = value.split('#', 1)[0].strip().lower().rstrip('.')
        if not value:
            continue
        if len(value) > 253 or '.' not in value or any(
            not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label)
            for label in value.split('.')
        ):
            raise ValueError('Invalid domain in local zones.list')
        if value not in domains:
            domains.append(value)
    if not domains:
        raise ValueError('zones.list must contain at least one domain')
    return domains


def zone_text(domain, address, serial):
    return f'''$TTL 300
@ IN SOA ns1.{domain}. hostmaster.{domain}. (
    {serial} ; serial
    3600 900 604800 300 )
@   IN NS ns1.{domain}.
@   IN A {address}
ns1 IN A {address}

; ISE placeholders: replace the example IPs and uncomment to enable.
; ise01.{domain}. IN A 192.0.2.11
; ise02.{domain}. IN A 192.0.2.12
; ise03.{domain}. IN A 192.0.2.13
'''


def options_text(interface, address):
    return f'''// Generated by pi-set-go from {interface}; regenerated on each run.
acl "trusted" {{
    127.0.0.1;
    {address.network};
}};

options {{
    directory "/var/cache/bind";
    listen-on {{ 127.0.0.1; {address.ip}; }};
    listen-on-v6 {{ none; }};
    allow-query {{ any; }};
    recursion yes;
    allow-recursion {{ trusted; }};
    allow-query-cache {{ trusted; }};
    allow-transfer {{ none; }};
    // Public forwarders from the reference; local zones are answered here.
    forward first;
    forwarders {{ 8.8.8.8; 8.8.4.4; }};
    dnssec-validation auto;
}};
'''


def reverse_networks(network):
    # DNS labels represent complete octets. Split instead of widening authority
    # beyond the detected subnet (/23 -> two /24s; /25 -> 128 host zones).
    prefix = ((network.prefixlen + 7) // 8) * 8
    return list(network.subnets(new_prefix=prefix))


def reverse_name(network):
    octets = str(network.network_address).split('.')[:network.prefixlen // 8]
    return '.'.join(list(reversed(octets)) + ['in-addr', 'arpa'])


def reverse_zone_text(network, address, domain, serial):
    origin = reverse_name(network)
    text = f'''; Reverse DNS for {network}, generated from the Ethernet subnet.
$TTL 300
@ IN SOA ns1.{domain}. hostmaster.{domain}. (
    {serial} ; serial
    3600 900 604800 300 )
@ IN NS ns1.{domain}.
'''
    if address in network:
        owner = address.reverse_pointer
        owner = '@' if owner == origin else owner[:-(len(origin) + 1)]
        text += f'{owner} IN PTR ns1.{domain}.\n'
    return text


def next_serial(target):
    if target.is_symlink():
        raise ValueError('Managed zone symlink requires manual review')
    old = target.read_text() if target.exists() else ''
    match = re.search(r'(?m)^\s*(\d+)\s*; serial', old)
    serial = max(int(time.time()), int(match[1]) + 1 if match else 1)
    if serial >= 2**32:
        raise ValueError('Zone serial exhausted; manual rollover required')
    return serial


def generated_zones(domains, address, managed):
    zones = {domain: zone_text(domain, address.ip, next_serial(managed / f'db.{domain}'))
             for domain in domains}
    # One canonical PTR for the Pi, using the first zone in the private list.
    for network in reverse_networks(address.network):
        name = reverse_name(network)
        if name in zones:
            raise ValueError(f'zones.list conflicts with automatically generated reverse zone {name}')
        zones[name] = reverse_zone_text(network, address.ip, domains[0], next_serial(managed / f'db.{name}'))
    return zones


def zone_declarations(zones, managed):
    return ''.join(f'zone "{name}" {{\n    type primary;\n    file "{managed / ("db." + name)}";\n'
                   '    allow-update { none; };\n};\n' for name in zones)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('output', type=Path)
    parser.add_argument('--interface')
    parser.add_argument('--dry-run', action='store_true', help='Detect the Ethernet IP and preview files without writing')
    parser.add_argument('--check-zones', action='store_true', help='Validate the local zone list only; no sudo or network required')
    args = parser.parse_args()
    try:
        domains = domains_from(args.output / 'zones.list')
    except (ValueError, OSError) as error:
        parser.error(str(error))
    if args.check_zones:
        print(f'Local DNS zone list validated: {len(domains)} zones.')
        return
    if not args.dry_run:
        if os.geteuid() != 0:
            parser.error('Run with sudo, or use --dry-run to preview on the Pi')
        for command in ('ip', 'named-checkzone', 'named-checkconf', 'systemctl'):
            if not shutil.which(command):
                parser.error(f'Missing {command}; install the required packages on the Pi first')
    addresses = json.loads(subprocess.check_output(['ip', '-j', '-4', 'address', 'show']))
    routes = json.loads(subprocess.check_output(['ip', '-j', '-4', 'route', 'show', 'default']))
    # Physical Ethernet includes USB adapters; exclude Wi-Fi and virtual bridges/veth.
    ethernet = {p.name for p in Path('/sys/class/net').iterdir()
                if (p / 'device').exists() and not (p / 'wireless').exists()
                and (p / 'type').read_text().strip() == '1'}
    interface, address = select_address(addresses, routes, ethernet, args.interface)
    root = Path('/etc/bind')
    local = root / 'named.conf.local'
    options = root / 'named.conf.options'
    managed = root / 'pi-set-go'
    if local.is_symlink() or options.is_symlink() or managed.is_symlink():
        raise ValueError('Custom BIND symlinks require manual review')
    include = 'include "/etc/bind/pi-set-go/zones.conf";'
    current_local = local.read_text() if local.exists() else ''
    active_include = re.search(r'(?m)^\s*' + re.escape(include) + r'\s*$', current_local)
    new_local = current_local if active_include else current_local.rstrip() + '\n\n' + include + '\n'
    new_options = options_text(interface, address)
    zones = generated_zones(domains, address, managed)
    declarations = zone_declarations(zones, managed)
    if args.dry_run:
        print(f'Detected {interface}: {address}')
        print(f'\n{options}:\n{new_options}')
        print(f'{local}:\n{new_local}')
        for name, text in zones.items():
            print(f'{managed / ("db." + name)}:\n{text}')
        print(f'{managed / "zones.conf"}:\n{declarations}')
        print('\nPreview only; no files written or services changed. Apply advances existing serials.')
        return
    backup = Path(tempfile.mkdtemp(prefix='pi-set-go-dns-', dir='/var/backups'))
    files = [local, options]
    owners = {p: (p.stat().st_uid, p.stat().st_gid) for p in files}
    for p in files:
        shutil.copy2(p, backup / p.name)
    had_managed = managed.exists()
    if had_managed:
        shutil.copytree(managed, backup / 'zones')
    print(f'DNS: {interface} = {address}; backup: {backup}', flush=True)
    try:
        managed.mkdir(mode=0o755, exist_ok=True)
        for name, text in zones.items():
            target = managed / f'db.{name}'
            target.write_text(text)
            target.chmod(0o644)
            subprocess.run(['named-checkzone', name, str(target)], check=True)
        zone_config = managed / 'zones.conf'
        if zone_config.is_symlink():
            raise ValueError('Managed include symlink requires manual review')
        zone_config.write_text(declarations)
        zone_config.chmod(0o644)
        local.write_text(new_local)
        options.write_text(new_options)
        subprocess.run(['named-checkconf', '-z'], check=True)
        subprocess.run(['systemctl', 'restart', 'named'], check=True)
        subprocess.run(['systemctl', 'is-active', '--quiet', 'named'], check=True)
    except Exception:
        for p in files:
            shutil.copy2(backup / p.name, p)
            os.chown(p, *owners[p])
        shutil.rmtree(managed, ignore_errors=True)
        if had_managed:
            shutil.copytree(backup / 'zones', managed)
        print('Restored DNS configuration; inspect named service status before restarting manually.')
        raise
    # Keep generated copies in the ignored local config directory for review.
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / 'zones').mkdir(exist_ok=True)
    (args.output / 'named.conf.local').write_text(new_local)
    (args.output / 'named.conf.options').write_text(new_options)
    (args.output / 'zones.conf').write_text(zone_config.read_text())
    for name in zones:
        shutil.copy2(managed / f'db.{name}', args.output / 'zones' / f'db.{name}')
    print('DNS configured. Point clients at the Ethernet IP; rerun after its address changes.')


if __name__ == '__main__':
    main()
